--
-- Copyright (c) 2019 AT&T Intellectual Property. All rights reserved.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--        https://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

USE AKRAINO;

CREATE TABLE IF NOT EXISTS BLUEPRINT (
	UUID		VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME		VARCHAR(36) NOT NULL,
	DESCRIPTION	VARCHAR(256),
	VERSION		VARCHAR(36),
	YAML		LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS REGION (
	UUID		VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME		VARCHAR(36) NOT NULL,
	DESCRIPTION	VARCHAR(256),
	PARENT  VARCHAR(36)
);

CREATE TABLE IF NOT EXISTS HARDWARE (
	UUID		VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME		VARCHAR(36) NOT NULL,
	DESCRIPTION	VARCHAR(256),
	YAML		LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS NODE (
	UUID		 VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME		 VARCHAR(36) NOT NULL,
	DESCRIPTION	 VARCHAR(256),
	HARDWARE     VARCHAR(36) NOT NULL,
	YAML		 LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS EDGESITE (
	UUID		VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME		VARCHAR(36) NOT NULL,
	DESCRIPTION	VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS EDGESITE_ARRAYS (
	UUID		VARCHAR(36) NOT NULL,
	FKEY		VARCHAR(36) NOT NULL,
	TYPE        CHAR NOT NULL,
	PRIMARY KEY (UUID, FKEY)
);

CREATE TABLE IF NOT EXISTS POD (
	UUID		VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME		VARCHAR(36) NOT NULL,
	DESCRIPTION	VARCHAR(256),
	STATE       VARCHAR(12) NOT NULL,
	BP_UUID     VARCHAR(36) NOT NULL,
	ES_UUID	    VARCHAR(36) NOT NULL,
	YAML		LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS POD_EVENTS (
	UUID		VARCHAR(36) NOT NULL,
	EVENTTIME	TIMESTAMP NOT NULL,
	LEVEL		VARCHAR(8) NOT NULL,
	EVENTMSG	LONG VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS POD_WORKFLOWS (
	UUID		VARCHAR(36) NOT NULL,
	NAME		VARCHAR(36) NOT NULL,
	RUNINDEX	INTEGER,
	STARTTIME	TIMESTAMP NOT NULL,
	ENDTIME		TIMESTAMP NULL,
	YAML		LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS USERS (
	UUID		VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME		VARCHAR(36) NOT NULL,
	DESCRIPTION	VARCHAR(256),
	PWHASH		VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
	USER_UUID	VARCHAR(36) NOT NULL,
	ROLE_UUID	VARCHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLES (
	UUID		VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME		VARCHAR(36) NOT NULL,
	DESCRIPTION	VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS ROLE_ATTRIBUTES (
	ROLE_UUID	VARCHAR(36) NOT NULL,
	ATTRIBUTE	VARCHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS SESSIONS (
	COOKIE		VARCHAR(72) NOT NULL PRIMARY KEY,
	USERID		VARCHAR(36) NOT NULL,
	EXPIRES		BIGINT
);

CREATE INDEX IF NOT EXISTS POD_EVENTS_INDEX ON POD_EVENTS (UUID);
CREATE INDEX IF NOT EXISTS POD_WORKFLOWS_INDEX ON POD_WORKFLOWS (UUID);
